name: Build & Push JMeter Docker

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: sazhnovperformance
  IMAGE_NAME: sql-worker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with plugins baked in
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:0.1 .

      - name: Push to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:0.1
